### ISSUE TITLE
Crear modelo Student

### ISSUE THREAD

**Issue by perezamora** [kindelan/PooVuelingCapas#1]
Realizar las modificiaciones para crear un modelo Student que herede de modelo VuelingObject, el modelo vueling object tiene un guid unico de objeto.

**Comment by kindelan** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Configuracion Trello Github para asociar issues (Aprox 1h)](https://trello.com/c/lmCRnA0L/1-configuracion-trello-github-para-asociar-issues-aprox-1h)

**Comment by kindelan** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Crear Capa Model Vueling (Aprox 2h)](https://trello.com/c/rdMbgS5X/2-crear-capa-model-vueling-aprox-2h)

**Comment by kindelan** [comment]
subido el model
