### ISSUE TITLE
Crear capa presentacion obtener datos

### ISSUE THREAD

**Issue by perezamora** [kindelan/PooVuelingCapas#2]
Realizar al codificación de formulario obtención de campos  y comunicar con capa Business.

**Comment by perezamora** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Crear Capa Presentacion (Aprox 2h)](https://trello.com/c/aaWhnnJZ/3-crear-capa-presentacion-aprox-2h)

**Comment by kindelan** [comment]
hecho boss!
