### ISSUE TITLE
Construir metodo Add AlumnoBl y realizar calculos atributos Edat y fecha creacion.

### ISSUE THREAD

**Issue by perezamora** [kindelan/PooVuelingCapas#3]
Implementar metodo ADD capa business

**Comment by perezamora** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Comunicar Presentacion con Business (Aprox 2h)](https://trello.com/c/i366goZo/4-comunicar-presentacion-con-business-aprox-2h)

**Comment by kindelan** [comment]
voy tronko

**Comment by kindelan** [comment]
hecho
