### ISSUE TITLE
Implementar clase AlumnoTxtDao

### ISSUE THREAD

**Issue by perezamora** [kindelan/PooVuelingCapas#4]
Implementar metodos de la clase AlumnoTxtDao, insertar alumno en el fichero TXT.

**Comment by perezamora** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Realizar capa Dao acceso ficheros (Aprox 4h)](https://trello.com/c/4HIYIGIZ/5-realizar-capa-dao-acceso-ficheros-aprox-4h)

**Comment by kindelan** [comment]
tanca neng
